apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: {{ .Values.namespace }} 
  labels:
    {{ toYaml .Values.commonLabels | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{ toYaml .Values.commonLabels | nindent 4 }}
  ports:
    {{ toYaml .Values.commonPorts | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.namespace }} 
  labels:
    {{ toYaml .Values.commonLabels | nindent 4 }}
spec:
  selector:
    {{ toYaml .Values.commonLabels | nindent 4 }}
  ports:
    {{ toYaml .Values.commonPorts | nindent 4 }}